import type { PricingPlanRow } from '@/components/product-catalog/productCatalogPage.types'

export const VERCEL_PRO_PLAN: PricingPlanRow = {
  id: -1001,
  name: "Pro",
  description: "For professional developers and small teams",
  billingPeriod: "Monthly",
  amount: "$20/seat + usage",
  currency: "USD",
  status: "live",
  draft: {
    planName: "Pro",
    planDescription: "For professional developers and small teams",
    planCurrency: "USD",
    planLookupKey: "vercel-pro",
    planTaxTreatment: "Included in prices",

    planPriceGroups: [
      { id: 0, name: "Usage", serviceInterval: "Monthly" },
    ],

    planRateCards: [
      // Flat product: Pro Seat (not in a price group)
      { id: 0, name: "Pro Seat", rates: [{ id: 0, name: "" }] },
      // Usage products inside the "Usage" price group
      { id: 1, name: "Functions — Active CPU", rates: [{ id: 1, name: "" }], priceGroupId: 0 },
      { id: 2, name: "Functions — Memory", rates: [{ id: 2, name: "" }], priceGroupId: 0 },
      { id: 3, name: "Functions — Invocations", rates: [{ id: 3, name: "" }], priceGroupId: 0 },
      { id: 4, name: "Edge Requests", rates: [{ id: 4, name: "" }], priceGroupId: 0 },
      { id: 5, name: "Fast Data Transfer", rates: [{ id: 5, name: "" }], priceGroupId: 0 },
      { id: 6, name: "Image Optimization", rates: [{ id: 6, name: "" }], priceGroupId: 0 },
      { id: 7, name: "Blob Storage", rates: [{ id: 7, name: "" }], priceGroupId: 0 },
      { id: 8, name: "Web Analytics", rates: [{ id: 8, name: "" }], priceGroupId: 0 },
      { id: 9, name: "ISR", rates: [{ id: 9, name: "" }], priceGroupId: 0 },
      { id: 10, name: "Edge Config", rates: [{ id: 10, name: "" }], priceGroupId: 0 },
    ],
    planRates: [],
    activePlanRateCardId: 0,
    planRateUsage: {},
    planRateUnitPrices: { 0: "20.00", 1: "0.128", 2: "0.0106", 3: "0.60", 4: "2.00", 5: "0.15", 6: "0.05", 7: "0.023", 8: "3.00", 9: "0.40", 10: "3.00" },
    planRateTiers: {},
    planRateTierToValues: {},
    planRateTierUnitPrices: {},
    planRateTierFlatFees: {},
    planRateIncludeTax: {},
    planRateCurrencies: {},
    planRateActiveCurrencyId: {},
    planUsageScenarioRates: [],

    planCreditGrants: [{ id: 0, name: "Included usage credit" }],
    planSubscriptionFees: [],
    planExpandedRateCards: { 0: true, 1: true, 2: true, 3: true, 4: true, 5: true, 6: true, 7: true, 8: true, 9: true, 10: true },

    showRateCardAdvanced: false,
    showRateAdvanced: false,
    showCreditAdvanced: false,
    showSubscriptionFeeAdvanced: false,

    rateCardLookupKeys: {},
    rateCardServicingPeriods: { 0: "Flat", 1: "Usage-based", 2: "Usage-based", 3: "Usage-based", 4: "Usage-based", 5: "Usage-based", 6: "Usage-based", 7: "Usage-based", 8: "Usage-based", 9: "Usage-based", 10: "Usage-based" },
    rateCardMetadataRows: {},
    rateCardMetadataValues: {},

    rateMeters: { 1: "function_active_cpu_hrs", 2: "function_memory_gb_hrs", 3: "function_invocations", 4: "edge_requests", 5: "fast_data_transfer_gb", 6: "image_transformations", 7: "blob_storage_gb", 8: "web_analytics_events", 9: "isr_reads", 10: "edge_config_reads" },
    availablePlanMeterOptions: ["function_active_cpu_hrs", "function_memory_gb_hrs", "function_invocations", "edge_requests", "fast_data_transfer_gb", "image_transformations", "blob_storage_gb", "web_analytics_events", "isr_reads", "edge_config_reads"],
    planRateMeterConfigs: {},

    ratePriceTypes: { 0: "One-time" },
    rateSellAs: {},
    rateUnitLabels: { 0: "seat", 1: "hour", 2: "GB-hr", 3: "1M invocations", 4: "1M requests", 5: "GB", 6: "1K transforms", 7: "GB", 8: "100K events", 9: "1M reads", 10: "1M reads" },
    rateTaxCodes: {},
    rateItemLookupKeys: {},
    rateItemMetadataRows: {},
    rateItemMetadataValues: {},
    rateSettingsMetadataRows: {},
    rateSettingsMetadataValues: {},

    creditGrantAmounts: { 0: "20.00" },
    creditGrantPeriods: { 0: "Monthly" },
    creditGrantApplications: {},
    creditGrantLookupKeys: {},

    subscriptionFeeAmounts: {},
    subscriptionFeePeriods: {},
    subscriptionFeePriceTypes: {},
    subscriptionFeeSellAs: {},
    subscriptionFeeUnitLabels: {},
    subscriptionFeeTaxCodes: {},
    subscriptionFeeItemLookupKeys: {},
    subscriptionFeeFeeLookupKeys: {},
    subscriptionFeeItemMetadataRows: {},
    subscriptionFeeFeeMetadataRows: {},
    subscriptionFeeItemMetadataValues: {},
    subscriptionFeeFeeMetadataValues: {},
  },
}

export const VERCEL_ENTERPRISE_PLAN: PricingPlanRow = {
  id: -1002,
  name: "Enterprise",
  description: "For large teams with advanced security and compliance needs",
  billingPeriod: "Yearly",
  amount: "$99/seat + usage",
  currency: "USD",
  status: "live",
  draft: {
    planName: "Enterprise",
    planDescription: "For large teams with advanced security and compliance needs",
    planCurrency: "USD",
    planLookupKey: "vercel-enterprise",
    planTaxTreatment: "Included in prices",

    planPriceGroups: [
      { id: 0, name: "Usage", serviceInterval: "Monthly" },
    ],

    planRateCards: [
      { id: 0, name: "Enterprise Seat", rates: [{ id: 0, name: "" }] },
      { id: 1, name: "Functions — Active CPU", rates: [{ id: 1, name: "" }], priceGroupId: 0 },
      { id: 2, name: "Functions — Memory", rates: [{ id: 2, name: "" }], priceGroupId: 0 },
      { id: 3, name: "Functions — Invocations", rates: [{ id: 3, name: "" }], priceGroupId: 0 },
      { id: 4, name: "Edge Requests", rates: [{ id: 4, name: "" }], priceGroupId: 0 },
      { id: 5, name: "Fast Data Transfer", rates: [{ id: 5, name: "" }], priceGroupId: 0 },
      { id: 6, name: "Image Optimization", rates: [{ id: 6, name: "" }], priceGroupId: 0 },
      { id: 7, name: "Blob Storage", rates: [{ id: 7, name: "" }], priceGroupId: 0 },
      { id: 8, name: "Web Analytics", rates: [{ id: 8, name: "" }], priceGroupId: 0 },
      { id: 9, name: "ISR", rates: [{ id: 9, name: "" }], priceGroupId: 0 },
      { id: 10, name: "Edge Config", rates: [{ id: 10, name: "" }], priceGroupId: 0 },
    ],
    planRates: [],
    activePlanRateCardId: 0,
    planRateUsage: {},
    planRateUnitPrices: { 0: "99.00" },
    planRateTiers: {},
    planRateTierToValues: {},
    planRateTierUnitPrices: {},
    planRateTierFlatFees: {},
    planRateIncludeTax: {},
    planRateCurrencies: {},
    planRateActiveCurrencyId: {},
    planUsageScenarioRates: [],

    planCreditGrants: [{ id: 0, name: "Included usage credit" }],
    planSubscriptionFees: [],
    planExpandedRateCards: { 0: true },

    showRateCardAdvanced: false,
    showRateAdvanced: false,
    showCreditAdvanced: false,
    showSubscriptionFeeAdvanced: false,

    rateCardLookupKeys: {},
    rateCardServicingPeriods: { 0: "Flat", 1: "Usage-based", 2: "Usage-based", 3: "Usage-based", 4: "Usage-based", 5: "Usage-based", 6: "Usage-based", 7: "Usage-based", 8: "Usage-based", 9: "Usage-based", 10: "Usage-based" },
    rateCardMetadataRows: {},
    rateCardMetadataValues: {},

    rateMeters: { 1: "function_active_cpu_hrs", 2: "function_memory_gb_hrs", 3: "function_invocations", 4: "edge_requests", 5: "fast_data_transfer_gb", 6: "image_transformations", 7: "blob_storage_gb", 8: "web_analytics_events", 9: "isr_reads", 10: "edge_config_reads" },
    availablePlanMeterOptions: ["function_active_cpu_hrs", "function_memory_gb_hrs", "function_invocations", "edge_requests", "fast_data_transfer_gb", "image_transformations", "blob_storage_gb", "web_analytics_events", "isr_reads", "edge_config_reads"],
    planRateMeterConfigs: {},

    ratePriceTypes: { 0: "Recurring" },
    rateSellAs: {},
    rateUnitLabels: { 0: "seat" },
    rateTaxCodes: {},
    rateItemLookupKeys: {},
    rateItemMetadataRows: {},
    rateItemMetadataValues: {},
    rateSettingsMetadataRows: {},
    rateSettingsMetadataValues: {},

    creditGrantAmounts: { 0: "" },
    creditGrantPeriods: { 0: "Monthly" },
    creditGrantApplications: {},
    creditGrantLookupKeys: {},

    subscriptionFeeAmounts: {},
    subscriptionFeePeriods: {},
    subscriptionFeePriceTypes: {},
    subscriptionFeeSellAs: {},
    subscriptionFeeUnitLabels: {},
    subscriptionFeeTaxCodes: {},
    subscriptionFeeItemLookupKeys: {},
    subscriptionFeeFeeLookupKeys: {},
    subscriptionFeeItemMetadataRows: {},
    subscriptionFeeFeeMetadataRows: {},
    subscriptionFeeItemMetadataValues: {},
    subscriptionFeeFeeMetadataValues: {},
  },
}

export const VERCEL_HOBBY_PLAN: PricingPlanRow = {
  id: -1000,
  name: "Hobby",
  description: "For personal projects and experimentation",
  billingPeriod: "Monthly",
  amount: "$0/seat",
  currency: "USD",
  status: "live",
  draft: {
    planName: "Hobby",
    planDescription: "For personal projects and experimentation",
    planCurrency: "USD",
    planLookupKey: "vercel-hobby",
    planTaxTreatment: "Included in prices",

    planPriceGroups: [
      { id: 0, name: "Usage", serviceInterval: "Monthly" },
    ],

    planRateCards: [
      { id: 1, name: "Functions — Active CPU", rates: [{ id: 1, name: "" }], priceGroupId: 0 },
      { id: 2, name: "Functions — Memory", rates: [{ id: 2, name: "" }], priceGroupId: 0 },
      { id: 3, name: "Functions — Invocations", rates: [{ id: 3, name: "" }], priceGroupId: 0 },
      { id: 4, name: "Edge Requests", rates: [{ id: 4, name: "" }], priceGroupId: 0 },
      { id: 5, name: "Fast Data Transfer", rates: [{ id: 5, name: "" }], priceGroupId: 0 },
      { id: 6, name: "Image Optimization", rates: [{ id: 6, name: "" }], priceGroupId: 0 },
      { id: 7, name: "Blob Storage", rates: [{ id: 7, name: "" }], priceGroupId: 0 },
      { id: 8, name: "Web Analytics", rates: [{ id: 8, name: "" }], priceGroupId: 0 },
      { id: 9, name: "ISR", rates: [{ id: 9, name: "" }], priceGroupId: 0 },
      { id: 10, name: "Edge Config", rates: [{ id: 10, name: "" }], priceGroupId: 0 },
    ],
    planRates: [],
    activePlanRateCardId: 1,
    planRateUsage: {},
    planRateUnitPrices: { 1: "0", 2: "0", 3: "0", 4: "0", 5: "0", 6: "0", 7: "0", 8: "0", 9: "0", 10: "0" },
    planRateTiers: {},
    planRateTierToValues: {},
    planRateTierUnitPrices: {},
    planRateTierFlatFees: {},
    planRateIncludeTax: {},
    planRateCurrencies: {},
    planRateActiveCurrencyId: {},
    planUsageScenarioRates: [],

    planCreditGrants: [],
    planSubscriptionFees: [],
    planExpandedRateCards: {},

    showRateCardAdvanced: false,
    showRateAdvanced: false,
    showCreditAdvanced: false,
    showSubscriptionFeeAdvanced: false,

    rateCardLookupKeys: {},
    rateCardServicingPeriods: { 1: "Usage-based", 2: "Usage-based", 3: "Usage-based", 4: "Usage-based", 5: "Usage-based", 6: "Usage-based", 7: "Usage-based", 8: "Usage-based", 9: "Usage-based", 10: "Usage-based" },
    rateCardMetadataRows: {},
    rateCardMetadataValues: {},

    rateMeters: { 1: "function_active_cpu_hrs", 2: "function_memory_gb_hrs", 3: "function_invocations", 4: "edge_requests", 5: "fast_data_transfer_gb", 6: "image_transformations", 7: "blob_storage_gb", 8: "web_analytics_events", 9: "isr_reads", 10: "edge_config_reads" },
    availablePlanMeterOptions: ["function_active_cpu_hrs", "function_memory_gb_hrs", "function_invocations", "edge_requests", "fast_data_transfer_gb", "image_transformations", "blob_storage_gb", "web_analytics_events", "isr_reads", "edge_config_reads"],
    planRateMeterConfigs: {},

    ratePriceTypes: {},
    rateSellAs: {},
    rateUnitLabels: { 1: "hour", 2: "GB-hr", 3: "1M invocations", 4: "1M requests", 5: "GB", 6: "1K transforms", 7: "GB", 8: "100K events", 9: "1M reads", 10: "1M reads" },
    rateTaxCodes: {},
    rateItemLookupKeys: {},
    rateItemMetadataRows: {},
    rateItemMetadataValues: {},
    rateSettingsMetadataRows: {},
    rateSettingsMetadataValues: {},

    creditGrantAmounts: {},
    creditGrantPeriods: {},
    creditGrantApplications: {},
    creditGrantLookupKeys: {},

    subscriptionFeeAmounts: {},
    subscriptionFeePeriods: {},
    subscriptionFeePriceTypes: {},
    subscriptionFeeSellAs: {},
    subscriptionFeeUnitLabels: {},
    subscriptionFeeTaxCodes: {},
    subscriptionFeeItemLookupKeys: {},
    subscriptionFeeFeeLookupKeys: {},
    subscriptionFeeItemMetadataRows: {},
    subscriptionFeeFeeMetadataRows: {},
    subscriptionFeeItemMetadataValues: {},
    subscriptionFeeFeeMetadataValues: {},
  },
}

export const VERCEL_PRICING_PLANS: PricingPlanRow[] = [
  VERCEL_HOBBY_PLAN,
  VERCEL_PRO_PLAN,
  VERCEL_ENTERPRISE_PLAN,
]
