import type { ProductRow } from '@/components/product-catalog/productCatalogPage.types'

export const VERCEL_PRODUCTS: ProductRow[] = [
  {
    id: -2001,
    name: "Serverless Functions",
    description: "On-demand compute for API routes and server-side logic",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "function_invocations",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "Total volume",
      tiers: [1, 2, 3],
      tierToValues: { 1: "100000", 2: "1000000", 3: "10000000" },
      tierUnitPrices: { 1: "0.00", 2: "0.60", 3: "0.40" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL FUNCTIONS",
      unitLabel: "invocation",
      metadataRows: [],
      featureRows: [1, 2, 3],
      featureValues: { 1: "Auto-scaling to zero", 2: "10s default / 300s max duration (Pro)", 3: "Node.js, Go, Python, Ruby runtimes" },
    },
  },
  {
    id: -2002,
    name: "Edge Functions",
    description: "Low-latency compute at the edge, globally distributed",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "edge_function_invocations",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.65" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL EDGE",
      unitLabel: "invocation",
      metadataRows: [],
      featureRows: [1, 2],
      featureValues: { 1: "Global edge network", 2: "Sub-millisecond cold starts" },
    },
  },
  {
    id: -2003,
    name: "Bandwidth",
    description: "Data transfer from Vercel's edge network to end users",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "bandwidth_gb",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "Total volume",
      tiers: [1, 2],
      tierToValues: { 1: "1000", 2: "10000" },
      tierUnitPrices: { 1: "0.15", 2: "0.10" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL BANDWIDTH",
      unitLabel: "GB",
      metadataRows: [],
      featureRows: [1, 2],
      featureValues: { 1: "100 GB included with Pro", 2: "Global CDN distribution" },
    },
  },
  {
    id: -2004,
    name: "Image Optimization",
    description: "Automatic image resizing, format conversion, and CDN caching",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "image_optimizations",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.01" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL IMAGES",
      unitLabel: "optimization",
      metadataRows: [],
      featureRows: [1, 2, 3],
      featureValues: { 1: "WebP/AVIF auto-conversion", 2: "Responsive srcset generation", 3: "5,000 included with Pro" },
    },
  },
  {
    id: -2005,
    name: "Web Analytics",
    description: "Privacy-friendly, real-user analytics with Core Web Vitals",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "web_analytics_events",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.0003" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL ANALYTICS",
      unitLabel: "event",
      metadataRows: [],
      featureRows: [1, 2],
      featureValues: { 1: "25,000 events included with Pro", 2: "No cookie banner required" },
    },
  },
  {
    id: -2006,
    name: "KV Storage",
    description: "Durable, low-latency key-value store at the edge",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "kv_reads",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.002" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL KV",
      unitLabel: "read",
      metadataRows: [],
      featureRows: [1, 2, 3],
      featureValues: { 1: "Redis-compatible API", 2: "Global replication", 3: "REST and native protocols" },
    },
  },
  {
    id: -2007,
    name: "Postgres",
    description: "Serverless Postgres database with branching and connection pooling",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "postgres_compute_hrs",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.10" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL POSTGRES",
      unitLabel: "compute-hour",
      metadataRows: [],
      featureRows: [1, 2, 3],
      featureValues: { 1: "Serverless connection pooling", 2: "Database branching for previews", 3: "Automatic scaling" },
    },
  },
  {
    id: -2008,
    name: "Blob Storage",
    description: "Object storage for files, images, and static assets",
    billingPeriod: "Monthly",
    amount: "Usage-based",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Usage-based",
      usageBasis: "Sum of usage during period",
      meter: "blob_storage_gb",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "0.03" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL BLOB",
      unitLabel: "GB",
      metadataRows: [],
      featureRows: [1, 2],
      featureValues: { 1: "Global CDN distribution", 2: "Direct upload support" },
    },
  },
  {
    id: -2009,
    name: "Pro Seat",
    description: "Per-seat license for Pro plan access",
    billingPeriod: "Monthly",
    amount: "20.00",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Flat rate",
      usageBasis: "",
      meter: "",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "20.00" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL PRO SEAT",
      unitLabel: "seat",
      metadataRows: [],
      featureRows: [1],
      featureValues: { 1: "Full Pro plan access per team member" },
    },
  },
  {
    id: -2002,
    name: "Enterprise Seat",
    description: "Per-seat license for Enterprise plan access",
    billingPeriod: "Monthly",
    amount: "99.00",
    currency: "USD",
    imageUrl: null,
    status: "live",
    draft: {
      chargeFrequency: "Monthly",
      pricingModel: "Flat rate",
      usageBasis: "",
      meter: "",
      billingPeriod: "Monthly",
      includeTax: "Included in prices",
      tieredBy: "None",
      tiers: [1],
      tierToValues: {},
      tierUnitPrices: { 1: "99.00" },
      tierFlatFees: {},
      productTaxCode: "",
      statementDescriptor: "VERCEL ENTERPRISE SEAT",
      unitLabel: "seat",
      metadataRows: [],
      featureRows: [1],
      featureValues: { 1: "Full Enterprise plan access per team member" },
    },
  },
]
